nome: Windows-RDP

em: workflow_dispatch

empregos:
  construir:

    em funcionamento: windows-latest
    tempo limite de minutos: 999999999999

    passos:
    - nome: Baixar Ngrok.
      corrida: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/start.bat -OutFile start.bat
 Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/wallpaper.png -OutFile papel de parede.png
 Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/wallpaper.bat -OutFile papel de parede.bat
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/loop.bat -OutFile loop.bat
    - nome: Download Launcher.
      corrida: |
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://github.com/DinhPhuc/windows-rdp/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"
    - nome: Extrair Arquivo Ngrok.
      executado: Expand-Archive ngrok.zip
    - nome: Connect Ngrok.
      executado: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ segredos. NGROK_AUTH_TOKEN }}
    - nome: Action Access RDP.
      corrida: | 
 Configuração-ItemProperty -Caminho 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
 Habilitar-NetFirewallRule -DisplayGroup "Área de trabalho remota"
 Configuração-itemProperty -Caminho 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nome "UserAuthentication" -Value 1
 copiar papel de parede.png D:\a\papel de parede.png
 copiar papel de parede.bat D:\a\papel de parede.bat
 copiar Nó.js.lnk C:\Users\Public\Desktop\Node.js.lnk
 copiar "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
 copiar "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"
    - nome: Fazendo túneis
      executar: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - nome: Conectar RDP CPU 2 Core - 7GB Ram - 256 SSD.
      execução: cmd /c start.bat
    - nome: Implementação bem sucedida! Você pode fechar a guia agora.
      execução: cmd /c loop.bat
